/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.api.gateway;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void getA() {
        Library rp = new Library();
        assertEquals("Should return a", rp.findWord("Once upon a time, there was a brave princess who..."), "a");
    }
}
